### ISSUE TITLE
full xslt3.0 processing

### ISSUE THREAD

**Issue by pahjbo** [robbert-harms/pyschematron#4]
you mention in your documentation that you cannot do xslt3 processing - are you aware of https://pypi.org/project/saxonche/ ?

**Comment by robbert-harms** [comment]
Hi pahjbo, 

Yes I am aware of that library. It is technically possible to use the XSLT processor of that library as an interpreter for functions in a Schematron. I chose not to do that for the simple reason that, if you need extensive XSLT support, it may be better to use an XSLT processor in the first place. PySchematron is very flexible though, you can define an own interpreter and add support for XSLT in that way. 

Does this answer your question?

**Comment by pahjbo** [comment]
Thanks @robbert-harms - I do have some of my schematron logic in xslt functions - so do need an XSLT processor - I am coming from Java, so was looking for something in Python that had already implemented some of the "housekeeping" associated with caching etc. I had just made the comment as your initial documentation implied (to me at least) that you had not yet included an XSLT processor because of the lack of XSLT>=2 processor in python.
